use_frameworks!

target 'FreeRDP_Cpp_Example' do
  pod 'FreeRDP_Cpp', :path => '../'

  target 'FreeRDP_Cpp_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
